In [2]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [5]:
dataFolder = 'input/'
dataFile = "iris.csv"
print(dataFile)

iris.csv


In [6]:
df = pd.read_csv(dataFile)
df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [8]:
print(X[0:5])
print(y[0:5])

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [9]:
print(X.shape)
print(y.shape)

(149, 4)
(149,)


In [10]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [11]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [12]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [14]:
print(X_train[0:5])

[[5.2 3.4 1.4 0.2]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [5.9 3.2 4.8 1.8]
 [5.1 3.8 1.5 0.3]]


In [15]:
print(y_train[0:5])

[[1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [16]:
print(X_test[0:5])

[[6.1 2.6 5.6 1.4]
 [6.5 3.2 5.1 2. ]
 [5.  2.  3.5 1. ]
 [5.5 2.4 3.7 1. ]
 [4.4 2.9 1.4 0.2]]


In [17]:
print(y_test[0:5])

[[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]]


In [28]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='tanh'),
    tf.keras.layers.Dense(10, activation='tanh'),
    tf.keras.layers.Dense(3, activation='tanh')
  ])
model

In [29]:
model.compile(optimizer='rmsprop',
              loss='MSE',
              metrics=['accuracy'])

In [30]:
model.fit(X_train, y_train, batch_size=50, epochs=100)


Epoch 1/100
3/3 [==============================] - 1s 5ms/step - loss: 0.7061 - accuracy: 0.4034
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 0.5978 - accuracy: 0.5882
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 0.5129 - accuracy: 0.6639
Epoch 4/100
3/3 [==============================] - 0s 4ms/step - loss: 0.4358 - accuracy: 0.6639
Epoch 5/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3692 - accuracy: 0.6639
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 0.3111 - accuracy: 0.6639
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 0.2661 - accuracy: 0.6639
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.2301 - accuracy: 0.6639
Epoch 9/100
3/3 [==============================] - 0s 8ms/step - loss: 0.2035 - accuracy: 0.6639
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.1834 - accuracy: 0.6639
Epoch 11/100
3/3 [===========

In [31]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.05261195823550224
Test accuracy: 1.0


In [32]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 84ms/step


array([[ 0.09805939,  0.13803412,  0.677544  ],
       [-0.09274536,  0.4464965 ,  0.659817  ],
       [ 0.07079601,  0.6121169 ,  0.09518898],
       [ 0.0933433 ,  0.68150073, -0.04082772],
       [ 0.8486778 ,  0.15430655, -0.04788566],
       [-0.02410395,  0.03499967,  0.7646939 ],
       [-0.20437117,  0.4518957 ,  0.68122184],
       [ 0.08854571,  0.6285904 ,  0.2630812 ],
       [-0.01112294,  0.25593254,  0.6062836 ],
       [ 0.0691068 ,  0.61540186,  0.4049649 ],
       [ 0.8544632 ,  0.16110872, -0.07443041],
       [ 0.84539217,  0.18164037, -0.07878979],
       [ 0.0729652 ,  0.5532221 ,  0.4003851 ],
       [ 0.8338958 ,  0.22246407, -0.11864825],
       [ 0.86402243,  0.10969275, -0.02162798],
       [ 0.00215032,  0.46690768,  0.5247032 ],
       [-0.11015961,  0.29063246,  0.7241738 ],
       [ 0.02552037,  0.71117324,  0.01037167],
       [ 0.8835128 ,  0.06462622, -0.01131927],
       [ 0.8963173 ,  0.00360771,  0.03399301],
       [ 0.74086136,  0.3824105 , -0.209

In [33]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
Predicted: [2 2 1 1 0 2 2 1 2 1 0 0 1 0 0 2 2 1 0 0 0 0 1 0 1 1 1 0 0 2]
